### ISSUE TITLE
Homepage Design

### ISSUE THREAD

**Issue by innovativedmm** [Smona/wp.thepoliticalrev.org#25]
- [x] Need to remove all blog post from homepage. 
- [x] Need to create a custom homepage.
- [ ] Custom homepage mockup: [Mock-Up](https://trello.com/c/t9TMw64Z)
- [ ] [Website assets ](https://drive.google.com/drive/folders/0B1szWO5ETx3jNEg2WEI4MzJDSWM?usp=sharing)(images)

**Comment by Smona** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Homepage](https://trello.com/c/t9TMw64Z/175-homepage)
